-- PlantPulse 01: database, warehouse and core tables
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PLANTPULSE_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS PLANTPULSE;
CREATE SCHEMA IF NOT EXISTS PLANTPULSE.OPS;

-- Lets Cortex models hosted in other regions serve this account (needed on some trial regions)
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

USE WAREHOUSE PLANTPULSE_WH;
USE SCHEMA PLANTPULSE.OPS;

CREATE OR REPLACE TABLE MACHINES (
  MACHINE_ID          VARCHAR PRIMARY KEY,
  LINE                VARCHAR,
  LINE_NAME           VARCHAR,
  MACHINE_TYPE        VARCHAR,
  INSTALL_DATE        DATE,
  IDEAL_CYCLE_TIME_S  NUMBER(6,1)
);

CREATE OR REPLACE TABLE SENSOR_READINGS (
  MACHINE_ID   VARCHAR,
  TS           TIMESTAMP_NTZ,
  TEMPERATURE  FLOAT,   -- °C
  VIBRATION    FLOAT,   -- mm/s RMS
  PRESSURE     FLOAT,   -- bar
  RPM          FLOAT
);

CREATE OR REPLACE TABLE PRODUCTION_LOG (
  MACHINE_ID   VARCHAR,
  SHIFT_DATE   DATE,
  SHIFT        VARCHAR,  -- A / B / C
  PLANNED_MIN  FLOAT,
  RUN_MIN      FLOAT,
  TOTAL_COUNT  NUMBER,
  GOOD_COUNT   NUMBER
);

CREATE OR REPLACE TABLE MAINTENANCE_EVENTS (
  MACHINE_ID    VARCHAR,
  TS            TIMESTAMP_NTZ,
  EVENT_TYPE    VARCHAR,  -- PLANNED / FAILURE
  DOWNTIME_MIN  NUMBER,
  NOTES         VARCHAR
);
