-- PlantPulse 04: Snowflake Cortex AI
USE SCHEMA PLANTPULSE.OPS;

-- 1) GenAI work orders straight from SQL with Cortex COMPLETE
CREATE OR REPLACE VIEW AI_WORK_ORDERS AS
SELECT MACHINE_ID, RISK_LEVEL, RISK_SCORE,
       SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
         'You are a reliability engineer. Write a concise maintenance work order (asset, priority, '
         || 'suspected cause, actions, parts, estimated downtime) for this machine. Data: '
         || OBJECT_CONSTRUCT(*)::VARCHAR) AS WORK_ORDER
FROM MACHINE_RISK
WHERE RISK_LEVEL IN ('HIGH', 'MEDIUM');

SELECT * FROM AI_WORK_ORDERS;

-- 2) Plain-English summary of the plant's state for the shift handover
SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large2',
  'Summarize plant health for a shift-handover in 5 bullets. Risk data: '
  || (SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))::VARCHAR FROM MACHINE_RISK)) AS SHIFT_HANDOVER;

-- 3) (Optional) Snowflake ML anomaly detection on vibration, trained on older "normal" data
CREATE OR REPLACE VIEW VIB_TRAIN AS
  SELECT MACHINE_ID, TS, VIBRATION FROM SENSOR_READINGS
  WHERE TS <  DATEADD(day, -3, (SELECT MAX(TS) FROM SENSOR_READINGS))
    AND NOT (MACHINE_ID = 'M-L2-02' AND TS BETWEEN DATEADD(day, -19, CURRENT_TIMESTAMP()) AND DATEADD(day, -14, CURRENT_TIMESTAMP()));
CREATE OR REPLACE VIEW VIB_RECENT AS
  SELECT MACHINE_ID, TS, VIBRATION FROM SENSOR_READINGS
  WHERE TS >= DATEADD(day, -3, (SELECT MAX(TS) FROM SENSOR_READINGS));

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION VIB_DETECTOR(
  INPUT_DATA        => SYSTEM$REFERENCE('VIEW', 'VIB_TRAIN'),
  SERIES_COLNAME    => 'MACHINE_ID',
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME    => 'VIBRATION',
  LABEL_COLNAME     => '');

CALL VIB_DETECTOR!DETECT_ANOMALIES(
  INPUT_DATA        => SYSTEM$REFERENCE('VIEW', 'VIB_RECENT'),
  SERIES_COLNAME    => 'MACHINE_ID',
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME    => 'VIBRATION');

SELECT SERIES AS MACHINE_ID, COUNT_IF(IS_ANOMALY) AS ML_ANOMALIES_72H
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
GROUP BY 1 ORDER BY 2 DESC;
